### ISSUE TITLE
behavior of the first div below #nav

### ISSUE THREAD

**Issue by richardrood** [jbutko/stickyNavbar.js#17]
I realy like this but i can't get the behavior of the first div below #header and nav. 
There is allways a margin above that div when navigating from bottom to the fist div below the nav div
The margin seems to be the same as the #header itself.

This issue is also in your example 
First navigate to the section contact an then to section downloads

is there a sollution for this?

thanks, Richard

**Comment by mhunt** [comment]
This issue seems to still happen when there is no 'Home' Link.  I'm using the latest version from a bower install.

Scenario:

About
Contact

Home
About
Contact

After you scroll down with your mouse manually, and then click 'About'. It takes you up to the top of the page. If you add 'Home', and hide that li, then everything works because the navigation no longer takes you back to the top.

**Comment by jbutko** [comment]
hi @mhunt, I pushed new version few days ago with rewritten scrolling logic. Please test if the issue with 'Home' is fixed or if it's fine. Here's latest version:
```html
<script src="//cdn.jsdelivr.net/stickynavbar.js/1.2.0/jquery.stickyNavbar.min.js"></script>
